### ISSUE TITLE
'day_first=True' should be the default for parse

### ISSUE THREAD

**Issue by JayTurnr** [kennethreitz/maya#105]
https://github.com/kennethreitz/maya/blob/79d017fdcfc6e6b88c721c2e2b9aafcee5c141c1/maya/core.py#L610

A total of 4170 million people in the world work with the day first, whereas only 705 million uses month first. On top of that, 1970 million people use year first. day first SHOULD be the default.

https://en.wikipedia.org/wiki/Date_format_by_country#Legends

**Comment by kennethreitz** [comment]
Too late now.
