### ISSUE TITLE
Can't be imported when installed in a virtualenvwrapper environment

### ISSUE THREAD

**Issue by Singletoned** [kennethreitz/maya#11]
I've installed maya on OSX in a virtualenv using virtualenvwrapper with python 2.7 and 3.5.  On both of them maya can't be imported even though it's dependencies can (eg humanize) ("ImportError: No module named 'maya'" is reported).  I haven't had this problem with any other package in several years of using virtualenvwrapper for all of my environments, so it's quite unusual.

Installing into a manually created virtualenv works fine.

**Comment by Singletoned** [comment]
Actually, it turns out installing into a manually created virtualenv also fails, so its not virtualenvwrapper specific.

**Comment by kennethreitz** [comment]
this should now be fixed by #12
