### ISSUE TITLE
MayaDT - MayaDT should yield a duration

### ISSUE THREAD

**Issue by b-jazz** [kennethreitz/maya#116]
As of now, you can subtract a duration from a date, but you can't find out the duration between two different dates by subtracting one date from another.

**Comment by kennethreitz** [comment]
I agree

**Comment by tbarron** [comment]
If I understand this correctly, we want the following test to pass:

```
def test_mayaDT_sub():
    assert maya.when('tomorrow') - maya.now() == timedelta(1)
    assert maya.now - maya.when('tomorrow') == timedelta(-1)
```

Is that right?
