### ISSUE TITLE
Python 3.6 not supported

### ISSUE THREAD

**Issue by JayTurnr** [kennethreitz/maya#125]
```
Traceback (most recent call last):
  File "lib/trainerdex/client.py", line 4, in <module>
    import maya
  File "lib/maya/__init__.py", line 1, in <module>
    from .core import *
  File "lib/maya/core.py", line 18, in <module>
    import dateparser
  File "lib/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "lib/dateparser/date.py", line 10, in <module>
    import regex as re
  File "lib/regex.py", line 400, in <module>
    import _regex_core
  File "lib/_regex_core.py", line 21, in <module>
    import _regex
ModuleNotFoundError: No module named '_regex'
```

It seems that trying to use regex on Python 3.6 is causing some issues. It's being imported by your module.

**Comment by timofurrer** [comment]
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import maya
>>>
```

:thinking: 

Could you install `maya` into a virtualenv and provide the versions of all packages you've installed there (`pip freeze`) ?

In any case - It's a dependency of `maya` importing `_regex` and not `maya` itself. Therefore we should create the issue there :)

**Comment by kennethreitz** [comment]
I only use maya on 3.6 :)

**Comment by JayTurnr** [comment]
Turns out it's because python3.6-dev wasn't installed, only python3.6, thus regex wouldn't install via pip. Mildly annoying but once I figured it out everything was okay! (Ubuntu)
