### ISSUE TITLE
is package `ruamel.yaml` really required?

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/maya#134]
`setup.py`, `Pipfile` and `maya/core.py` reference `ruamel.yaml` but I did not find any direct usage of it in the code.

Is it really needed?

Does it relate to ruamel.ordereddict?

Issue #57 is mentioning `ruamel.yaml` but there is no clear reason for it.

**Comment by timofurrer** [comment]
`ruamel.yaml` is removed with #136
