### ISSUE TITLE
consider using `tox` for testing

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/maya#137]
Currently testing is supported by:
- travis
- Makefile

Anyway, running local tests for multiple python versions is either impossible or very difficult as one would have to arrange local Travis test.

My proposal is:
- add tox based testing: this will allow running all the tests locally without much difficulties
- consider modification of travis.yml to reuse the tox.ini. This is not strictly required, but it would simplify updating the test suite.

Personally I like `tox` a lot and at the same time I really enjoy `pipenv`. One area, where I am in doubt searching for obvious way to do things is testing multiple python interpreters when pipenv is in place with it's `Pipfile` and possibly `Pipfile.lock`

So far I use `tox.ini` from which I refer to required package via `requirements.txt`.

Anyway, whatever way of installing dependencies will be used with tox.ini, I believe it would simplify multiple interpreter test significantly.

**Comment by timofurrer** [comment]
> add tox based testing: this will allow running all the tests locally without much difficulties

I've just added a `tox.ini`.

> consider modification of travis.yml to reuse the tox.ini. This is not strictly required, but it would simplify updating the test suite.

I'd rather use `pipenv` as common testing tool for `tox` and `travis`. I think we leave it as it is right now.

Thanks for the suggestion 🎉

**Comment by vlcinsky** [comment]
@timofurrer well done.

I run `tox` and all works well on my machine (py2.7, py3.5, py3.6 - py3.4 is missing here, that is my setup). All tests passed, second run runs relatively fast, now I feel more comfortable.

Thanks.
