### ISSUE TITLE
Provide feedback on how the time was parsed

### ISSUE THREAD

**Issue by LAlbertalli** [kennethreitz/maya#14]
Hi,

I've tried the library and it seems to work pretty well. A problem I noticed, though, is that I'm not able to see what was parsed and update it.

For example:
```
import maya

maya.when("today",timezone='America/Los_Angeles').datetime()
>>> datetime.datetime(2016, 12, 18, 18, 53, 32, 221615, tzinfo=<UTC>)

maya.when("today at 10:55 AM",timezone='America/Los_Angeles').datetime()
>>> datetime.datetime(2016, 12, 18, 18, 55, tzinfo=<UTC>)
```
This is great except that 'today' means now if, for my specific application, I want 'today' to mean today at midnight.

It would be really nice if the library could provide in the returned object some flags to specify it parsed a day, or parsed a time or both. So that I could eventually append something to my string (e.g: " at midnight").

**Comment by kennethreitz** [comment]
it sounds like you want `maya.now()`, which will return the UTC representation of now. 

You can then export a datetime to another timezone (like your local one) with `mayadt.datime(to_timezone='US/Pacific')

**Comment by LAlbertalli** [comment]
No, that's not my problem.

My problem is if I just input "today" I have no knowledge on what it has interpreted as "today". Imagine this use to parse a string submitted by a user for example in a data visualization application. If he types today as the starting point of the chart, I want to specify at midnight. But if he types "today at 10 AM" I don't want to specify the time because it is clear.

Makes more sense now?

Thanks
L.
