### ISSUE TITLE
Incorrect date when using .when with weekdays

### ISSUE THREAD

**Issue by alxwrd** [kennethreitz/maya#146]
hello! :wave:

There appears to be an issue with `maya.when()` when using weekday names.

```python
>>> today = maya.now()
>>> print(today)
'Sun, 15 Apr 2018 16:58:03 GMT'

>>> tomorrow = maya.when("monday", prefer_past=False)
>>> print(tomorrow)
'Mon, 09 Apr 2018 00:00:00 GMT'
```

[**dateparser**](https://github.com/scrapinghub/dateparser) seems to handle this correctly, but only when the setting 'PREFER_DATES_FROM' is set to 'future'.

```python
>>> dateparser.parse("monday")
datetime.datetime(2018, 4, 9, 0, 0)

>>> dateparser.parse("monday", settings={"PREFER_DATES_FROM": "future"})
datetime.datetime(2018, 4, 16, 0, 0)

>>> dateparser.parse("Apr 16")
datetime.datetime(2018, 4, 16, 0, 0)

>>> dateparser.parse("Apr 16", settings={"PREFER_DATES_FROM": "past"})
datetime.datetime(2017, 4, 16, 0, 0)
```

The default setting for dateparser appears to be `"current_period"` from [dateparser/dateparser_data/settings.py](https://github.com/scrapinghub/dateparser/blob/master/dateparser_data/settings.py).

As the only way to alter the 'PREFER_DATES_FROM' setting is change `prefer_past`, there is currently no way to get the future day in this instance.

I'll open a PR with a failing test.

**Comment by timofurrer** [comment]
Hi! Thanks for contribution! 

> I'll open a PR with a failing test.

Great! :tada: 

@kennethreitz what about exposing the `PREFER_DATES_FROM` setting from `dateparser` via the `maya.when()` API?

Something like:

```python
maya.when('monday', prefer_dates_from='past')
```

**Comment by alxwrd** [comment]
@timofurrer  I had thought:

```diff
-def when(string, timezone='UTC', prefer_past=False):
+def when(string, timezone='UTC', prefer_past=None):

-    if prefer_past:
+    if prefer_past is False:
+        settings['PREFER_DATES_FROM'] = 'future'
+    if prefer_past is True:
         settings['PREFER_DATES_FROM'] = 'past'

     dt = dateparser.parse(string, settings=settings)
```
This should allow all three of dateparsers options of 'current_period', 'future', and 'past'.

**Comment by timofurrer** [comment]
Sounds even better!
I'm looking forward to accept the change in the PR you've already made ;)

**Comment by timofurrer** [comment]
I might have second thought about the proposed API. 
The thing is, that for me, setting `prefer_past=False` doesn't intuitively mean that it should prefer the `future`. It would just mean that not the `past` should be preferred and therefore the `current_period` is used. Which isn't the case. 

Having both arguments `prefer_past` and `prefer_future` available leads to inconsistencies and therefore not really an option. Which leads us to `prefer_dates_from=` argument. I know it's kinda verbose but the best I can come up with right now. And thoughts?

**Comment by alxwrd** [comment]
I agree.

My thoughts behind keeping `prefer_past` was that it's a non breaking change.

I think _because_ `prefer_dates_from` is more verbose, it might be nicer.

```diff
-def when(string, timezone='UTC', prefer_past=False):
+def when(string, timezone='UTC', prefer_dates_from='current_period'):

    settings = {
         'TIMEZONE': timezone,
         'RETURN_AS_TIMEZONE_AWARE': True,
         'TO_TIMEZONE': 'UTC',
+        'PREFER_DATES_FROM': prefer_dates_from,
     }
-    if prefer_past:
-        settings['PREFER_DATES_FROM'] = 'past'
+
     dt = dateparser.parse(string, settings=settings)
     if dt is None:
         raise ValueError('invalid datetime input specified.')
```

Let me know and I can push up some changes ✨

**Comment by timofurrer** [comment]
Yes, let's do that! @kennethreitz any thoughts on that one?

**Comment by timofurrer** [comment]
Done in #147
