### ISSUE TITLE
Comparison with Arrow

### ISSUE THREAD

**Issue by syndbg** [kennethreitz/maya#15]
What are the pros/cons against https://github.com/crsmithdev/arrow ?

Just wondering since you start a new library that may split the community between the two libraries w/o an idea which is better in which scenarios.

Just my two cents as a Python developer.

**Comment by kennethreitz** [comment]
arrow is a great library, but isn't what I wanted in a datetime library. In many ways, it's better than Maya for certian things, in some ways, in my opinion, it's not. 

I just wanted to try to make a sane API for datetimes that made sense to me for all the things I'd ever want to do. Arrow doesn't do all of those things. Maya does. 

I think the projects compliment each-other, personally. Maya is great for parsing websites, for example.  Arrow supports floors and ceilings and spans of dates, which Maya does not at all.

**Comment by syndbg** [comment]
@kennethreitz Superb. I think it makes sense to add these paragraphs to the README.md so that it's clear :)

**Comment by kennethreitz** [comment]
Good idea!

**Comment by syndbg** [comment]
Resolved by 07a3e814a272110e8b5558ac399dfbe7c2b6494a. Closing
