### ISSUE TITLE
Subtracting two MayaDT objects gives incorrect delta.

### ISSUE THREAD

**Issue by jgaines** [kennethreitz/maya#151]
```python
print(maya.when('tomorrow') - maya.when('today'))
```
Prints out:
```
86400 days, 0:00:00
```
To fix this, in the MayaDT.subtract_date method, specify that you're setting the seconds of the timedelta object you create:
```python
    def subtract_date(self, **kwargs):
        """Returns a timedelta object with the duration between the dates"""
        return timedelta(seconds=self.epoch - kwargs['dt'].epoch)
```
This will make at least one of your tests fail (same fix should be applied to it, pass the calculated seconds in as seconds:
```python
@pytest.mark.usefixtures("frozen_now")
def test_mayaDT_sub():
    now = maya.now()
    then = now.add(days=1)
    assert then - now == timedelta(seconds=24 * 60 * 60)
    assert now - then == timedelta(seconds=-24 * 60 * 60)
```

**Comment by matmunn** [comment]
Why not submit a PR if you've already written out the fix?

**Comment by timofurrer** [comment]
Thanks for the contribution! I've fixed it in 8468dd2

@jgaines you are more than welcome to submit a PR next time :beers:

**Comment by jgaines** [comment]
Heh, sorry, end of a long day didn't have the steam left to do it proper. ;)

**Comment by timofurrer** [comment]
No problem :) :tada:
