### ISSUE TITLE
Can set default timezone?

### ISSUE THREAD

**Issue by nickhell** [kennethreitz/maya#158]
Can set default timezone?
I see, change timezone from UTC to US/Eastern, like `maya.now().datetime(to_timezone='US/Eastern', naive=True)`.
But i must call it everytime, can i set default timezone? Then in my application, i created the timezone of datetime is US/Eastern.

**Comment by nickhell** [comment]
I see `maya.now().local_datetime()`. my issue is solved.

**Comment by Owyn** [comment]
> I see `maya.now().local_datetime()`. my issue is solved.

does it still work for you? 

It errors for me : `AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'zone'`
