### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by impredicative** [kennethreitz/maya#163]
Is Python 3.7 supported? I couldn't install it because I got a `regex` package installation error.

**Comment by timofurrer** [comment]
On what platform are you on?
It works perfectly fine for me and travis as well: https://travis-ci.org/kennethreitz/maya/jobs/429542623

Could you please let us know about the exact error you get?

**Comment by impredicative** [comment]
I am on Ubuntu 16.04. Its an error compiling the `regex` package. I will follow up with that project if I can. I am basically glad to hear that it's supposed to work on Python 3.7. Thanks.
