### ISSUE TITLE
Interactive demo for `maya` code examples

### ISSUE THREAD

**Issue by martinzugnoni** [kennethreitz/maya#167]
Hello @kennethreitz,

I've been recently taking a look at `maya` and found it really interesting. I'm even thinking about adding it in our curriculum to teach our students at https://rmotr.com/ (co-founder and teacher here). It might be interesting to use it in comparison with the built-in `datetime` module.

While looking at the code examples in the README file I thought it would be great to provide some interactive demo that people can use to play with the library before committing to download and install it locally.

> A demo is worth a thousand words 😉

I spent a few minutes compiling all `maya` examples into a Jupyter Notebook file, and adapted it in a way that we can open it with a small service we have at RMOTR to launch Jupyter environments online. No account or subscription required to use it, so it's pretty convenient for people that wants to get hands on the library with a low entrance barrier. Note that `maya` is already installed when the env is loaded, so people can start using it right away.

The result is what you can see in my fork of the repo (see the new "Demo" section):
https://github.com/martinzugnoni/maya

Do you think that having such interactive demo would help people to know and use `maya`?
Let's use this issue as a kick off to start a discussion. Nothing here is written in stone and we can change everything as you wish.

I hope you like it, and I truly appreciate any feedback.

thanks.

**Comment by timofurrer** [comment]
Hi @martinzugnoni 

Thanks for the awesome idea and the work you've put into this! 🎉 
I, personally, really like what you did and would be happy to merge a PR :) - but let's wait for @kennethreitz's feedback

**Comment by martinzugnoni** [comment]
Hi @timofurrer! Thanks for the quick response.

I'm happy to open a PR if @kennethreitz agrees. Note that the current "Open demo" button points to my fork (under @martinzugnoni). I should change it to point to the original repo, so we all keep contributing to the same code base.

**Comment by martinzugnoni** [comment]
@timofurrer @kennethreitz did you guys have some time to double check the DEMO Notebook? If you have an initial feeling that this is viable I can put some more effort and time to write a more tuned version with the associated PR. Just confirm me if I should move forward with this idea ;-)

**Comment by timofurrer** [comment]
I'm always getting a "Not Found" error when visiting https://notebooks.rmotr.com/demo/gh/martinzugnoni/maya

However, as I've already stated in my first comment - I would be happy to see that demo online and a link in maya's README. We just need to make sure that it's up-to-date and maintain it properly.

**Comment by martinzugnoni** [comment]
@timofurrer thanks for reporting, the problem was solved. Sounds great! Then I will post a pull-request soon and we can discuss details there.

Unless examples in the DEMO notebook get deprecated, or you guys change something in the `maya` interface, we won't need much effort to keep everything up to date.

**Comment by timofurrer** [comment]
> Then I will post a pull-request soon and we can discuss details there.

Sounds great. I'm looking forward to it!
