### ISSUE TITLE
`datetime()` always setting tz to UTC even if `to_timezone` says otherwise

### ISSUE THREAD

**Issue by lbolla** [kennethreitz/maya#19]
I find the below confusing:

    In [72]: maya.when('2016-01-01').datetime(to_timezone='US/Eastern')
    Out[72]: datetime.datetime(2015, 12, 31, 19, 0, tzinfo=<UTC>)

Why, if `datetime()` is called using `to_timezone='US/Eastern'`, the resulting datetime object has `tz_info=UTC`?
Note that the resulting time is correctly UTC New Year in US/Eastern, but the tzinfo is wrong.
It's as if the resulting timezone was "replaced" rather than converted.

**Comment by kennethreitz** [comment]
ah, this is a bug

**Comment by kennethreitz** [comment]
`v0.1.3` was just released, which fixes this bug.

**Comment by kennethreitz** [comment]
also added a test
