### ISSUE TITLE
Compatibility with/subclassing datetime

### ISSUE THREAD

**Issue by brianjpetersen** [kennethreitz/maya#2]
I really love that you're doing this and hope it doesn't take years off your life 😊  Assuming it all comes together, it'll be a great contribution to the Python ecosystem - it's really needed!

One problem I've come across with other datetime replacements is that they don't pass ```issubclass(type(d), datetime.datetime)``` or ```isinstance(d, datetime.datetime)```.  Unfortunately, many commonly used third-party libraries (especially true for serialization) don't use duck typing the way you'd hope, and you end up having to marshall the convenience class back to a vanilla datetime object.  This is a pain and leads to a lot of aggravation (for me at least)!

Philosophically, do you dislike the idea of making this (reasonably) backwards compatible with the std library datetime module?  Subclassing datetime is a bit of a pain as I recall, but it may be possible to make the ```isinstance``` and ```issubclass``` checks work by (ab)using the ```abc``` module.  

Interested in your thoughts, and keep fighting the good fight!

**Comment by kennethreitz** [comment]
I don't think so, I like the current API, where it renders datetimes easily.
