### ISSUE TITLE
Install issue; install error?

### ISSUE THREAD

**Issue by bears34egc** [kennethreitz/maya#22]
I've used PIP and the setup.py file to install and came across the same issue.

Searching for python-dateutilruamel.yaml
Reading https://pypi.python.org/simple/python-dateutilruamel.yaml/
Couldn't find index page for 'python-dateutilruamel.yaml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for python-dateutilruamel.yaml
error: Could not find suitable distribution for Requirement.parse('python-dateutilruamel.yaml')

**Comment by joaoleveiga** [comment]
It was a missing comma. It will be fixed with #23

**Comment by kennethreitz** [comment]
this should now be fixed!
