### ISSUE TITLE
Wrapper around strftime

### ISSUE THREAD

**Issue by browniebroke** [kennethreitz/maya#47]
I'm using this library to test a REST API where one of the fields I'm submitting is a date of birth, as a string. It currently looks like:

```python
dob = maya.when("20 years ago").datetime()
dob_str = datetime.strftime(dob, "%Y-%m-%d")
```

It would be nicer if I could just do something like:
```python
dob_str = maya.when("20 years ago").as_text("%Y-%m-%d")
```

Would you be open to that? I suggested `as_text`, as I find the `strftime` not "for humans" (I personally had a hard time to remember it), I'm open to feedback on that name.

**Comment by kennethreitz** [comment]
I think the best practice for this now is to utilize the existing `datetime` methods, e.g. 

```
dob_str = maya.when("20 years ago").datetime <<< do formatting here
