### ISSUE TITLE
Erratic results

### ISSUE THREAD

**Issue by stucka** [kennethreitz/maya#48]
My first try I got an error. datetime() and iso8601() give similarly accurate results, but slang_date() fails.

>>> import maya
>>> maya.when('saturday').slang_date()
'Feb 03'
>>> maya.when('saturday').datetime()
datetime.datetime(2017, 2, 4, 0, 0, tzinfo=<UTC>)

**Comment by stucka** [comment]
I'm in a timezone problem, looks like.
```maya.when('Saturday noon EST').slang_date()``` does work and gives the correct date.

But should slang_date be assuming just a date, as a raw date, is meant to be midnight UTC, but then apparently adjust for local time?

**Comment by kennethreitz** [comment]
"saturday" == "saturday" at midnight, UTC time.

**Comment by kennethreitz** [comment]
you should likely provide a timezone, e.g. `maya.when('saturday', timezone='US/Eastern')`

**Comment by stucka** [comment]
You are a scholar and a gentleman. Thank you.
