### ISSUE TITLE
Incomplete ISO8601 parsing support

### ISSUE THREAD

**Issue by sdispater** [kennethreitz/maya#49]
The support for ISO8601 parsing is incomplete. Here are some valid ISO8601 strings that will raise an error or will return the wrong result:

* `20161001T1430.4+05:30` gives `2016-10-01T08:30:30.400000+00:00` (should be `2016-10-01T09:00:00.400000+00:00`).
* `2016T14`
* `2016-10T14`
* `2012W05`
* `2012W055`
* `2012007`
* `2016-W07T09`

**Comment by kennethreitz** [comment]
let's fix this and write some tests!

**Comment by sdispater** [comment]
The thing is there is no library in python that can parse all of them (except `pendulum` but I don't think you want to set such a big library as a dependency of `maya`) so you would have to come up with an implementation from scratch in `maya`.

**Comment by kennethreitz** [comment]
i'm down with depending on penulum if it gets us what we need.

**Comment by kennethreitz** [comment]
pendulum might be a great way for us to add addition/subtraction as well!

**Comment by kennethreitz** [comment]
https://pendulum.eustace.io

**Comment by sdispater** [comment]
Oh! I never mentioned it but I am the author of `pendulum` :-)

So, I will see if I can cook up something and I will let you know.

**Comment by kennethreitz** [comment]
@sdispater nice to meet you! i think our projects can be friends :)

**Comment by kennethreitz** [comment]
@sdispater down for a google hangouts? i'm available now

**Comment by sdispater** [comment]
@kennethreitz Sure, why not :-)

**Comment by kennethreitz** [comment]
@sdispater i'm kenneth@heroku.com on hangouts. what's your username?

**Comment by sdispater** [comment]
@kennethreitz It's sebastien.eustace@gmail.com.
