### ISSUE TITLE
parse() doesn't properly parse exif data

### ISSUE THREAD

**Issue by jMyles** [kennethreitz/maya#52]
@kennethreitz, as an avid photographer, I expect you of all people to ensure that exif data is properly parsed.  ;-)

In this case, it appears that, if this is indeed a problem and I'm not just imagining things, it's a problem upstream.  I have opened an appropriate issue with pendulum:
https://github.com/sdispater/pendulum/issues/101

**Comment by kennethreitz** [comment]
thanks!

**Comment by kennethreitz** [comment]
https://github.com/sdispater/pendulum/issues/101

**Comment by emattiza** [comment]
sdispater/pendulum#102

Merged into develop, should be available next release

**Comment by sdispater** [comment]
Version `1.2.0` of pendulum has just been released with this feature included.

**Comment by kennethreitz** [comment]
\o/
