### ISSUE TITLE
Python 3: cmp() was removed

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/maya#58]
/cc @dgouldin

**Comment by Tafkas** [comment]
Also `reduce` has moved to `functools.reduce` in Python 3.

**Comment by kennethreitz** [comment]
@Tafkas would you be up for sending a PR fixing this? I normally add a `compat.py` file that we can import from.

**Comment by Tafkas** [comment]
@kennethreitz I submitted a PR. Not sure about the conventions. I am happy to alter it if need be.

**Comment by kennethreitz** [comment]
@Tafkas left feedback :)

**Comment by Tafkas** [comment]
I am on it

**Comment by kennethreitz** [comment]
`setup.py` will have to be updated to reflect that too!
