### ISSUE TITLE
Aligned intervals

### ISSUE THREAD

**Issue by imanhodjaev** [kennethreitz/maya#61]
Hi all, 
What do you think how useful will it be to have a feature which aligns intervals based on a given value?

### Use case

```
start = datetime.datetime(2017, 5, 25, 18, 21, 28)
end = datetime.datetime(2017, 5, 25, 18, 55, 28)

maya.interval(start, end, interval=FIVE_MIN, align=True)

# Then the produced sequence will look like
datetime.datetime(2017, 5, 25, 18, 20, 0)
datetime.datetime(2017, 5, 25, 18, 25, 0)
...
datetime.datetime(2017, 5, 25, 18, 55, 0)
```

The only restriction is that we have to support certain alignment intervals to make rounding operation easier like `5 minutes, 15 minutes, 1 hour`.

If this would be anyhow useful then I can make a PR.

Thanks.

**Comment by dgouldin** [comment]
Hi, @imanhodjaev.

Thanks for the idea. The method name may not be straightforward, but we've already included something like this: `MayaInterval.quantize`. (I realize we need some better docs and examples. I'll try to get on those as soon as I can.)

The `duration` argument defines the length of time to "snap" to relative to the epoch (midnight Jan 1, 1970). In this case, epoch is localized to the timezone you specify (or UTC by default) to give you the option to snap to durations relative to different timezones. The `snap_out` kwarg determines whether the start and end of the interval snap outward (resulting in a duration >= the original interval's duration) or inward (resulting in a duration <= the original interval's duration).

Hopefully that makes it a little clearer how to use `quantize` in the absence of ... actual documentation. 😉  Will that method suffice, or were you thinking of something different?

**Comment by imanhodjaev** [comment]
@dgouldin thank you for clarification. I see `quantize` is a little different. I  meant use cases when someone want to generate intervals relative to the beginning of an hour, 5 minute, a day intervals etc.

For example I want to generate 5 minute intervals relative to the beginning of current hour and a a start I give `datetime.now` and expect to have a generator which yields the following output

`start=17:11` `end=17:55`  with 5 minutes intervals and will have 12 datetime objects

1. `17:05`
2. `17:10`
3. `17:15`
4. `17:20`
5. `17:25`
6. `17:30`
7. `17:35`
8.  `17:40`
9. `17:45`
10. `17:50`
11. `17:55`
12. `18:00`

`start=17:11` `end=17:55`  with 15 minutes intervals and will have 5 datetime objects

1. `17:00`
2. `17:15`
3. `17:30`
4. `17:45`
5. `18:00`


Thanks.

**Comment by dgouldin** [comment]
Ah ok. For that, there's `MayaInterval.split`. The combination of the 2 should do what you want.

**Comment by imanhodjaev** [comment]
@dgouldin nice, thank you very much man!
