### ISSUE TITLE
rounding precision on add subtract calls

### ISSUE THREAD

**Issue by emattiza** [kennethreitz/maya#62]
Per #59 troubles, i did some digging, and it appears that the _epoch float is getting truncated between a now() invocation and a future add-subtract call, particularly rounding up from the 7th decimal digit. I added some unit tests which highlight this, both on the non-deterministic basis and with a forced failure. You may need to run a couple of times to duplicate. I'll submit a PR with the tests.

**Comment by kennethreitz** [comment]
i ended up rouding to the decimal point for all comparisons, and that fixed all our issues.

**Comment by emattiza** [comment]
i see! closing
