### ISSUE TITLE
Discussion: "==" operation on MayaInterval objects

### ISSUE THREAD

**Issue by moin18** [kennethreitz/maya#73]
Currently `==` operation is checked based on the value of `start` and `end` MayaDT objects and returns `True` if `start` and `end` are same for the passed `MayaInterval` object. Code:

```
def __eq__(self, maya_interval):
    return (
          self.start == maya_interval.start and
          self.end == maya_interval.end
    )

```

However, I feel that we should make the interval check based on the duration in seconds. For example:
```
MayaInterval(today, tomorrow) ==  MayaInterval(yesterday, today)
```

should return `True` because the interval is same. I think this way it will be more _Humanized_ based on the name "interval". if someone want to do check on `start` and `end` as well, they can still perform explicit check based on `start` and `end` attributes of the `MayaInterval` object.

If it sounds good, I can raise a PR along with allowing the other comparison operations on the `MayaInterval` objects.

**Comment by moin18** [comment]
Also, currently `MayaInterval` accepts `duration` as both in seconds and `datetime.timedelta`. We should force to allow duration only in seconds for the ease of the usage (less options, less confusion)

**Comment by kennethreitz** [comment]
I think an interval is two dates, not a duration.

**Comment by kennethreitz** [comment]
@dgouldin any thoughts?

**Comment by moin18** [comment]
General meaning of interval is "a space between two things" and in our case the number of seconds between two `MayaDT` objects. 

Though the current implementation of `MayaInterval` is also fine if we consider the identity of it is based on the `start`and `end` parameters. But I think it will be much better if `MayaInterval` objects are identified based the seconds. It is just my thought, and I am open for discussion.

**Comment by emattiza** [comment]
@moin18 I think the wording here would be [durations](https://en.wikipedia.org/wiki/ISO_8601#Durations), which would be a sub-class so-to-say of intervals (an interval consists of the time duration marked by two time points, whereas a duration could be defined w/o respect to any interval start or end). It would be useful and possible to create some sort of duration equivalency operation for interval objects given they do have a notion of a duration. But the strict equality of an Interval would be determined by equivalent start and end _epochs.

**Comment by moin18** [comment]
I think you guys make sense. We should keep `MayaInterval` as it is.

Closing this thread.
