### ISSUE TITLE
http://docs.python-maya.org/ is down

### ISSUE THREAD

**Issue by pzelnip** [kennethreitz/maya#85]
Going to http://docs.python-maya.org/ or the bare domain python-maya.org results in a DNS resolution error.

**Comment by timofurrer** [comment]
Duplicate of #83

**Comment by markfink** [comment]
+1
docu link from the header is broken

**Comment by kennethreitz** [comment]
i don't think this was ever setup, yet.

**Comment by kennethreitz** [comment]
i'll remove the link for now

**Comment by thornycrackers** [comment]
Is this getting set up any time soon?

**Comment by timofurrer** [comment]
I'm going to close those in favor of #56 . 
Once there is a solid documentation I guess we can put it up on http://docs.python-maya.org/
