### ISSUE TITLE
Support modifiers to beginning/end of day/week/etc. like Pendulum

### ISSUE THREAD

**Issue by HndrkMkt** [kennethreitz/maya#88]
I'm currently struggling with figuring out the beginning/end of a dynamically provided period (day, week, month, etc.) for a given MayaDT. How about supporting modifiers for this as already in place for [Pendulum](https://pendulum.eustace.io/docs/#modifiers) or [Arrow](http://arrow.readthedocs.io/en/latest/#arrow.arrow.Arrow.floor)? Would you be open to a PR?

**Comment by timofurrer** [comment]
Maya currently implements snap modifiers using https://github.com/zartstrom/snaptime:

```pycon
>>> dt = maya.when('Mon, 21 Feb 1994 21:21:42 GMT')
>>> dt.snap('@d+3h').rfc2822()
'Mon, 21 Feb 1994 03:00:00 GMT'
```

Is that what you are looking for?

**Comment by timofurrer** [comment]
I'm going to close this for now. 

If you want to follow up on this just let us know and we'll reopen the issue.

Thanks :tada:
