### ISSUE TITLE
raumel.yaml didn't work everywhere

### ISSUE THREAD

**Issue by pydanny** [kennethreitz/maya#9]
We dealt with it in Cookiecutter, it doesn't work on a lot of machines. Just letting you know.

**Comment by pydanny** [comment]
Oops, should have written title as "raumel.yaml doesn't"

**Comment by timofurrer** [comment]
> it doesn't work

... is a little bit broad. Do you remember what exactly *didn't work on a lot of machines*?

**Comment by kennethreitz** [comment]
I'll keep my ears open, thanks danny!

**Comment by pydanny** [comment]
Later when I'm at a computer I'll paste in links to the relevant issues from the Cookiecutter project.

**Comment by pydanny** [comment]
I see with issue #10 that you've begun to discover the hard-to-resolve problems that Cookiecutter users on Windows had with the YAML python libraries of pyYAML and raumel.yaml. Myself and @hackebrot spent quite a bit of time trying to help people in both the issue tracker and in Gitter.

Speaking of Gitter since it was discussed there we didn't document it as well as we might. In any case, here are some closed Cookiecutter issues I found on the subject:

* https://github.com/audreyr/cookiecutter/issues/557#issuecomment-150011970
* https://github.com/audreyr/cookiecutter/issues/569
* Solution was creating a pure Python parser of YAML called poyo: 
  * https://github.com/audreyr/cookiecutter/pull/621
  * https://github.com/hackebrot/poyo

If you want to support Windows users of Maya you might consider either using Poyo or simply drop YAML support. :man_shrugging:
