### ISSUE TITLE
RFE: add snap to time units (as in Splunk)

### ISSUE THREAD

**Issue by fenchu** [kennethreitz/maya#94]
Hi

After having worked with splunk for a long time, I've started to love their time to snap modifiers.
http://docs.splunk.com/Documentation/SplunkCloud/6.6.1/SearchReference/SearchTimeModifiers

Would love to see maya.when('-1d@d') (yesterday at 00:00:00)

There is a library for it in python:
https://github.com/zartstrom/snaptime

Thanks for an excellent library

**Comment by kennethreitz** [comment]
pull requests accepted!
