### ISSUE TITLE
MayaDT isn't hashable

### ISSUE THREAD

**Issue by jMyles** [kennethreitz/maya#95]
I'd like to be able to use a MayaDT as a key in a dict.  It's not immediately clear to me what needs to be done to make MayaDT hashable.

**Comment by jMyles** [comment]
Nevermind.  I had an old version of maya installed in the venv in which I was doing this.  I'll see myself out.

**Comment by moin18** [comment]
I think it is a nice suggestion. Since MayaDT is based on epoch time, using the `self._epoch` in the `hash` function is not a bad choice to make it hashable

**Comment by kennethreitz** [comment]
we apparently [already do that](https://github.com/kennethreitz/maya/blob/master/maya/core.py#L114) :)

**Comment by moin18** [comment]
Ohhh..nice. I checked the blame to confirm whether it was me to do that change :| Thankfully my memory is still in place, it wasn't me but YOU :D :D

**Comment by jMyles** [comment]
Just keep pilin' it on, boys.  This isn't humiliating enough yet.  :kissing_heart:
