### ISSUE TITLE
Add support for `time.time_struct` format

### ISSUE THREAD

**Issue by Miserlou** [kennethreitz/maya#98]
This looks like an awesome library, but unfortunately it doesn't seem like it supports the "9-tuple" [time.time_struct](https://docs.python.org/2/library/time.html#time.struct_time) format that `feedparser` and other older libraries use. It looks like there is a way to do `from_datetime`, but not `from_time_struct`. (For reference, I can do this in Arrow with `arrow.get(my_time_struct)` - but then I can't convert directly to RFCs like Maya can 😠).

Would you be interested in accepting this feature? That would allow me to use Maya as my time-core even when using older libraries.

**Comment by Miserlou** [comment]
(Internally it should be pretty simple, this works:

```python
dt = datetime.fromtimestamp(mktime(struct))
maya_dt = MayaDT.from_datetime(dt)
```
the trick would just be getting a validator right.)

I can work on this if it's in scope.

**Comment by Miserlou** [comment]
And, I guess more generally, a `load` method would be useful as I have multiple sources of dates that could be in various string formats and python formats. Currently, Maya requires knowledge of the date type when instantiating, it'd be great if I could just throw whatever I've got at it.

**Comment by kennethreitz** [comment]
`MayaDT.from_struct()` would be very welcome (or would be it `from_tuple`?)

**Comment by kennethreitz** [comment]
@Miserlou well that's what `maya.parse` is for — it'll just magically take any string and turn it into a `MayaDT` for you.

**Comment by kennethreitz** [comment]
If you can get everything into a string format, that would work well.
